//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calseare.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calseare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 扇形的面积是 的本地化字符串。
        /// </summary>
        public static string area_of_sector_is {
            get {
                return ResourceManager.GetString("area_of_sector_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseButton_Tip {
            get {
                return ResourceManager.GetString("CloseButton_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     public partial class MainWindow : Window
        ///    {
        ///        public MainWindow()
        ///        {
        ///            InitializeComponent();
        ///        }
        ///        private void Window_MouseLeftButtonDown_1(object sender, MouseButtonEventArgs e)
        ///        {
        ///            this.DragMove();
        ///        }
        ///
        ///        private void CloseButton_Click(object sender, RoutedEventArgs e)
        ///        {
        ///            System.Environment.Exit(0); 
        ///        }
        ///
        ///        private void Button_Click(object sender, RoutedEventArgs e)
        ///        {
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数值 的本地化字符串。
        /// </summary>
        public static string Input_value {
            get {
                return ResourceManager.GetString("Input_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的是否是数字 的本地化字符串。
        /// </summary>
        public static string Is_it_digital {
            get {
                return ResourceManager.GetString("Is_it_digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入圆心角度数 的本地化字符串。
        /// </summary>
        public static string LabelAngle_Text {
            get {
                return ResourceManager.GetString("LabelAngle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入扇形的半径 的本地化字符串。
        /// </summary>
        public static string LabelRadius_Text {
            get {
                return ResourceManager.GetString("LabelRadius_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        public static string MainButton_Text {
            get {
                return ResourceManager.GetString("MainButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以开始计算 的本地化字符串。
        /// </summary>
        public static string Start_calculation {
            get {
                return ResourceManager.GetString("Start_calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算扇形面积 的本地化字符串。
        /// </summary>
        public static string Title_Text {
            get {
                return ResourceManager.GetString("Title_Text", resourceCulture);
            }
        }
    }
}
